using Application.Common.Dtos;
using Application.Common.Response;
using DTO.Request.Admin;
using DTO.Response;
using DTO.Response.Admin;
using DTO.Response.Driver;
using DTO.Response.SystemValues;
using DTO.Response.User;

namespace Application.Abstraction.Repositories
{
    public interface IAdminRepository
    {
        Task<(List<GetStreetAndAreaMappedResponseDto>, int)> GetStreetAndAreaMapped(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<(List<GetAreasResponseDto>, int)> GetAreas(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<(List<GetSchoolYearsResponseDto>, int)> GetSchoolYears(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<(List<GetGenderResponseDto>, int)> GetGender(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<(List<GetDistrictResponseDto>, int)> GetDistrict(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<(List<GetSchoolsResponseDto>, int)> GetSchools(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<(List<GetBuildingResponseDto>, int)> GetBuilding(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<(List<GetCcResponseDto>, int)> GetCc(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<(List<GetChargeStructureResponseDto>, int)> GetChargeStructure(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<(List<GetNTResponseDto>, int)> GetNT(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<(List<GetBusTypeResponseDto>, int)> GetBusType(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<(List<GetRunTypeResponseDto>, int)> GetRunType(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<(List<GetDriverTypeResponseDto>, int)> GetDriverType(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<(List<GetDecductionAmountResponseDto>, int)> GetDecductionAmount(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<(List<GetSearchLocationResponseDto>, int)> GetSearchLocation(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<(List<GetSeasonFolderResponseDto>, int)> GetSeasonFolder(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<IList<GetSearchLocationResponseDto>> GetSearchLocation();
        Task<IList<GetAllRolesResponseDto>> GetRoles();
        Task<IList<GetPredefinedSMSMessagesResponseDto>> GetPredefinedSMSMessages();
        Task<IList<GetSeasonFolderResponseDto>> GetAllSeasonFolder();
        Task<List<Permissions>> GetPermissionsByRoleId(int roleId);
        Task<(List<GetBranchResponseDto>, int)> GetBranch(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<(List<GetAllGradeResponseDto>, int)> GetAllGrade(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<int> UpdatePermissionByRoleId(int permissionId, int roleId, string permissionType, bool canView, bool canEdit);
        Task<int> AddRole(string roleName);
        Task<int> AddStreetsAreaMapping(int id,string streetName, int areaId, int userId, int districtId);
        Task<int> AddAreas(int id, string areaName, int userId, string shortName);
        Task<int> AddSchoolYears(int id, int schoolYear, int numberOfStudents, int userId);
        Task<int> AddGender(int id,string gender, int userId);
        Task<int> AddDistrict(int id, string districtName, int userId);
        Task<int> AddSchool(int id, string schoolName, string legalName, int userId);
        Task<int> AddBuilding(int id, string address, int schoolId, int userId, string buildingName);
        Task<int> AddCC(int id, int cardnoxId, int familyId, int userId);
        Task<int> AddChargeStructure(int id, int districtId, int? ntId, bool isFunded, int userId, decimal price, int? schoolId);
        Task<int> AddNT(int id, string nTName, int userId);
        Task<int> AddBusType(AddBusTypeRequestDto addBusTypeRequestDto);
        Task<int> AddRunType(AddRunTypeRequestDto addRunTypeRequestDto);
        Task<int> UpdateFamilyTracking(UpdateFamilyTrackingRequestDto updateFamilyTrackingRequestDto);
        Task<int> UpdateProfile(UpdateProfileRequestDto updateProfile);
        Task<int> AddDriverType(int id, string driverType, decimal payRate, int userId);
        Task<int> AddDeductionAmount(int id, decimal amount, int userId);
        Task<int> AddSearchLocation(int id, string currntLocation, string currntLocationLongLat, int userId);
        Task<int> UpdateTrackingTime(UpdateTrackingTimeRequestDto updateTrackingTimeRequestDto);
        Task<int> AddUpdateBranch(AddUpdateBranchRequestDto addUpdateBranchRequestDto);
        Task<int> AddUpdateGrade(AddUpdateGradeRequestDto addUpdateGradeRequestDto);
        Task<int> AddSeasonFolder(AddSeasonFolderRequestDto addSeasonFolderRequestDto);
        Task<IList<GetAllDistrictsResponseDto>> GetAllDistricts();
        Task<GetTrackingTimeQueryResponseDto> GetTrackingTime();
        Task<IList<GetAllNTResponseDto>> GetAllNT();
        Task<IList<GetAllSchoolsResponseDto>> GetAllSchools();
        Task<int> UpdateChargeStructure(int id, bool isFunded);
        Task<IList<GetAreaListResponseDto>> GetAreaList();
        Task<int> DeleteStreetAreaMapping(int id);
        Task<int> DeleteArea(int id);
        Task<int> CheckDistrictBeforeDelete(int districtId);
        Task<int> CheckGenderBeforeDelete(int genderId);
        Task<int> CheckSchoolBeforeDelete(int schoolId);
        Task<int> CheckBuildingBeforeDelete(int buildingId);
        Task<int> CheckBranchBeforeDelete(int branchId);
        Task<int> CheckDriverTypeBeforeDelete(int driverTypeId);
        Task<int> CheckNTBeforeDelete(int nt);
        Task<int> CheckRouteTypeBeforeDelete(int routeType);
        Task<int> CheckStudentAreaRelation(int id);
        Task<int> DeleteSchoolYears(int id);
        Task<int> DeleteGender(int id);
        Task<int> DeleteDistrict(int id);
        Task<int> DeleteSchools(int id);
        Task<int> DeleteBuilding(int id);
        Task<int> DeleteCC(int id);
        Task<int> DeleteChargeStructure(int id);
        Task<int> DeleteNt(int id);
        Task<int> DeleteBusType(int id);
        Task<int> DeleteDriverType(int id);
        Task<int> DeleteBranch(int id);
        Task<int> DeleteRunType(DeleteRunTypeRequestDto deleteRunTypeRequestDto);
        Task<int> DeleteGrade(DeleteGradeRequestDto deleteGradeRequestDto);
        Task<int> DeleteSeasonFolder(DeleteSeasonFolderRequestDto deleteSeasonFolderRequestDto);
        Task<int> CheckSeasonFolderBeforeDelete(DeleteSeasonFolderRequestDto deleteSeasonFolderRequestDto);
        Task<int> CheckGradeBeforeDelete(DeleteGradeRequestDto deleteGradeRequestDto);
        Task<IList<GetAllGendersResponseDto>> GetAllGenders();
        Task<IList<GetAllBusTypeResponseDto>> GetAllBusType();
        Task<IList<GetAllRunTypeResponseDto>> GetAllRunType();
        Task<IList<GetBuildingListResponseDto>> GetBuildingList();
        Task<IList<GetStatesResponseDto>> GetStates(int id);
        Task<IList<GetCitiesResponseDto>> GetCities(int id);
        Task<IList<GetRouteTypeRequiredRulesResponseDto>> GetRouteTypeRequiredRules(int? routeTypeId);
        Task<int> AddLog(string message, string from, string messageType);
        Task<(List<GetAllFamilyDetailResponseDto>, int)> GetAllFamilyDetail(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<string> UpdateFamilyDetail(UpdateFamilyDetailRequestDto updateFamilyDetailRequestDto);
        Task<IList<GetAreaListResponseDto>> GetAllAreas();
        Task<int> ImportAreasKml(string areasJson);
        Task<int> UpdateGradeMapping(string gradeJson);
        Task<string> UpdateBulkGrade(UpdateBulkGradeDto updateBulkGradeDto);
        Task<string> SetRouteTypeRequiredRules(RouteTypeRequiredRulesDto routeTypeRequiredRulesDto);
        Task<IList<ExportFamilyListDto>> ExportFamilyList();
        Task<(List<GetMessageResponseDto>, int)> GetMessages(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task AddMessage(AddMessageRequestDto request);
        Task<int> DeleteMessage(DeleteMessageRequestDto request);
        Task<List<GetDaysResponseDto>> GetDay();
        Task<(List<GetDaysResponseDto>, int)> GetDays(string filterModel, ServerRowsRequest commonRequest, string getSort);
        Task<int> UpdateDayStatus(int id, bool isActive);
        Task<IList<RouteTypeDayDto>> GetRouteTypeDays(int routeTypeId);
        Task<int> UpdateRouteTypeExclusivePay(int id, bool exclusivelyPay);
        Task<(List<PredefinedColorDto>, int)> GetPredefinedColors( string filterModel, ServerRowsRequest commonRequest,string getSort);
        Task<int> AddUpdatePredefinedColor(AddUpdatePredefinedColorDto dto);
        Task<int> DeletePredefinedColor(int id);
        Task<List<PredefinedColorDto>> GetPredefinedColorsDropdown();
        Task<int> UpdateBusCharge(UpdateBusChargeRequestDto updateBusChargeRequestDto);
        Task<GetBusChargeQueryResponseDto> GetBusCharge();
    }
}
